feat: component commands
eclipse-velocitas/cli pull request #226
Opened 2024-03-19 12:33 UTC by doosuu

Adds commands to interact with project components: list, add and remove.

2024-03-19 12:47 UTC, dennismeister93 requested changes

2024-03-19 12:47 UTC, dennismeister93 commented on src/modules/project-config.ts
> +        this._components = this._components.filter((p) => p.id !== id);
p stands for?

2024-03-19 12:49 UTC, doosuu commented on src/modules/project-config.ts
> +        this._components = this._components.filter((p) => p.id !== id);
renamed

2024-03-20 06:00 UTC, dennismeister93 approved these changes

2024-03-20 06:00 UTC, merged